name: motivational
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_bloc: ^8.1.3
    #internet connection checker
  internet_connection_checker: ^1.0.0+1

  #data models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  equatable: ^2.0.5

  #functional programmings
  dartz: ^0.10.1
  
  #google fonts
  google_fonts: ^4.0.1

  #dependency injection
  injectable: ^2.1.0


  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test: 
    sdk: flutter


  flutter_lints: ^1.0.0
    #generators
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  flutter_gen_runner: ^5.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/core/assets/
  
  integrations:
    flutter_svg: true
