// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWaXst5sgSydg1fpdqe64eOaURKSgxx5g',
    appId: '1:398149048158:web:7175744b382f4de24ae1cf',
    messagingSenderId: '398149048158',
    projectId: 'motivator-53ae0',
    authDomain: 'motivator-53ae0.firebaseapp.com',
    storageBucket: 'motivator-53ae0.appspot.com',
    measurementId: 'G-LCD4ZXSY3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChD_87JVOgazvnhvp7u-4bjT3mDkohk6Q',
    appId: '1:398149048158:android:46e198945dd518214ae1cf',
    messagingSenderId: '398149048158',
    projectId: 'motivator-53ae0',
    storageBucket: 'motivator-53ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1a1Lg0g8PrNazQCs_qUBRd51LGXdQaU',
    appId: '1:398149048158:ios:e80cf3171231df1d4ae1cf',
    messagingSenderId: '398149048158',
    projectId: 'motivator-53ae0',
    storageBucket: 'motivator-53ae0.appspot.com',
    iosBundleId: 'com.example.motivational',
  );
}
