// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8hmMsWQlq7uDUpeEk_ofsWBIO_uw7iw',
    appId: '1:179648129338:web:79d8555c01ea91d76cc803',
    messagingSenderId: '179648129338',
    projectId: 'motivator-b1e0c',
    authDomain: 'motivator-b1e0c.firebaseapp.com',
    storageBucket: 'motivator-b1e0c.appspot.com',
    measurementId: 'G-ME6YX9152C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvIDfvbAchcKnuCAitg_wTXCEuPNOHBgo',
    appId: '1:179648129338:android:e15ef491871d3dd66cc803',
    messagingSenderId: '179648129338',
    projectId: 'motivator-b1e0c',
    storageBucket: 'motivator-b1e0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSASx2h8VAMo-Dm2HkCZtSuXh7xIFs8Js',
    appId: '1:179648129338:ios:e7595d8c581e9c656cc803',
    messagingSenderId: '179648129338',
    projectId: 'motivator-b1e0c',
    storageBucket: 'motivator-b1e0c.appspot.com',
    iosBundleId: 'com.veryfast.motivator',
  );

}